services:
  - type: web
    name: card76
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: APP_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 