services:
  - type: web
    name: pidr-game
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: APP_URL
        sync: false
      - key: DATA_BASE
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  - type: redis
    name: pidr-sessions
    ipAllowList: []
    plan: free 